name: expense_tracker
description: "Expense Tracker Application"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  dartz: ^0.10.1
  easy_localization: ^3.0.7
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  get_it: ^8.0.2
  hive: ^2.2.3
  intl: ^0.19.0
  json_annotation: ^4.9.0
  uuid: ^3.0.7
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/lang/